# Site settings
title:          Dev Store
description:    "프로그래밍을 하면서 얻은 지식이나 생각을 기록하는 저장소입니다."
baseurl:        ""
url:            "https://Shin-Hyunggyu.github.io"

# Author
author:
  name:         Shin-Hyunggyu
  email:        lofty87@daum.net
  img:          /assets/img/author.jpg

# Build settings
markdown:       kramdown
# highlighter:    rouge > monokai 적용

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:year:month:day/:title
paginate:       5
paginate_path: "/page/:num"
